nuts-foundation/nuts-specification

- rfc/rfc003-oauth2-authorization.md
More information about grant types and why the most common types are not suitable for the Nuts network.
> Suggest new abstract

- rfc/rfc003-oauth2-authorization.md
The specific identifier for the oauth endpoint type.
> added endpoint type

- rfc/rfc008-certificate-structure.md
CA's must have the same EKU as client/server certs
> RFC008 - Added EKU requirements to CA

- rfc/rfc006-distributed-registry.md
> RFC006: Dropped requirement that service ID must include type

- rfc/rfc006-distributed-registry.md
Closes #43 
when merged:
- create issue in nuts-node for resolving `oauth` endpoint
> Service endpoint references using query params

- rfc/rfc006-distributed-registry.md
> RFC006: Eleborate on controller authorization

- .gitbook/assets/rfc005/network.proto
Changes made after review of https://github.com/nuts-foundation/nuts-node/issues/225
> RFC005: Update protobuf definition after implementation review

- rfc/rfc006-distributed-registry.md
It could be explained different ways.
> made RFC006 - 3.2.3 more clear

- rfc/rfc006-distributed-registry.md
> RFC006: Complemented 5.2.5 with all spec'd verification relationships

- .gitbook/assets/rfc005/network.proto
- rfc/rfc005-distributed-network-using-grpc.md
> RFC005: Specified diagnostical request/response message

- .gitbook/assets/rfc005/network.proto
- rfc/rfc005-distributed-network-using-grpc.md
Impl: https://github.com/nuts-foundation/nuts-node/issues/337
> RFC005: Ported changes back after implementation

- rfc/rfc006-distributed-registry.md
Closes #37
next: nuts-foundation/nuts-node#341
> update DID Document deactivation

- rfc/rfc004-verifiable-transactional-graph.md
> fix rfc004 §3.4 contradiction

- rfc/rfc002-authentication-token.md
> Typos in rfc2

- rfc/rfc005-distributed-network-using-grpc.md
Closes #93 
added links for IPFS, Kademlia and SWIM
> added links for unknown terms

- rfc/rfc008-certificate-structure.md
> Add chapter about connection acception in rfc008

- rfc/rfc004-verifiable-transactional-graph.md
- rfc/rfc005-distributed-network-using-grpc.md
and renamed the term `leaf` to `head`
closes #90 
closes #92
> RFC004: made 'payload' more deterministic

- rfc/rfc006-distributed-registry.md
- rfc/rfc011-verifiable-credential.md
> Dealing with deactivated DID Documents

- rfc/rfc006-distributed-registry.md
> remove tid/tiv references from rfc006

- rfc/rfc003-oauth2-authorization.md
Based on the changes in: https://github.com/nuts-foundation/nuts-node/pull/391
> Update the oauth2 spec based on the changes in the flow

- rfc/rfc002-authentication-token.md
closes #109 
BSN is mentioned as example, main addition is the legislation context.
> describe constraint on user identification

- rfc/rfc017-distributed-network-grpc-v2.md
This PR describes how set reconciliation works and the individual steps.
It does not have a link to the protobuf spec.
@gerardsn I described the hashing to the (non-colliding) buckets using the rehashing method of the original paper. If we can't find any theory on using a random number generator, this would work as well?
> initial set reconciliation protocol

- rfc/rfc017-distributed-network-grpc-v2.md
After this, https://github.com/nuts-foundation/nuts-specification/issues/116 and https://github.com/nuts-foundation/nuts-specification/issues/137 are mostly fixed.
> RFC017: Describe exchange of private transactions

- rfc/rfc017-distributed-network-grpc-v2.md
> RFC017 change requirements on XOR

- rfc/rfc017-distributed-network-grpc-v2.md
> tie up loose ends for V2 protocol

- rfc/rfc014-authorization-credential.md
> added reference to RFC017 for §10 private TX of RFC014

- rfc/rfc017-distributed-network-grpc-v2.md
> clarify which transaction should be in a gossip msg

- rfc/rfc017-distributed-network-grpc-v2.md
> RFC017: Specify peer diagnostics (as in protocol v1)

- rfc/rfc017-distributed-network-grpc-v2.md
> changes to rfc017 musts to shoulds

- rfc/rfc017-distributed-network-grpc-v2.md
> RFC017: update IBLT description

- rfc/rfc017-distributed-network-grpc-v2.md
fixes #185 
This also updates the message flow in the protocol so that only 1 active conversation is needed at a time.
> RFC017: Extend TransactionList message and update flow

- rfc/rfc005-distributed-network-using-grpc.md
> Obsolete rfc005

- rfc/rfc017-distributed-network-grpc-v2.md
to make sure all TXs are send for the requested range.
> small changes to a conversation and range query

- rfc/rfc004-verifiable-transactional-graph.md
- rfc/rfc016-lamport-clock.md
See appendix A.2 of rfc004 for rationale
> changed requirement of TX to point to all prevs

- rfc/rfc013-vc-irma-proof.md
closes #169
note: the VP used from IRMA in the login contract has a different name.
> RFC013: renamed IRMA proof

- rfc/rfc003-oauth2-authorization.md
> add clock skew for access token request

- rfc/rfc003-oauth2-authorization.md
- rfc/rfc014-authorization-credential.md
> moved NutsAuthorizationCredential specific validations to RFC014

- rfc/rfc006-distributed-registry.md
> update RFC006: conflict detection for create transactions

- rfc/rfc011-verifiable-credential.md
> remove json-ld context limitation

- rfc/rfc011-verifiable-credential.md
Added it to RFC011 instead of RFC014
> added some info on JSON-LD Nuts context to RFC011

- SUMMARY.md
- rfc/rfc001-nuts-start-architecture.md
- rfc/rfc002-authentication-token.md
- rfc/rfc003-oauth2-authorization.md
- rfc/rfc004-verifiable-transactional-graph.md
- rfc/rfc005-distributed-network-using-grpc.md
- rfc/rfc006-distributed-registry.md
- rfc/rfc008-certificate-structure.md
- rfc/rfc011-verifiable-credential.md
- rfc/rfc012-nuts-organization-credential.md
- rfc/rfc013-vc-irma-proof.md
- rfc/rfc014-authorization-credential.md
- rfc/rfc015-node-identity.md
- rfc/rfc017-distributed-network-grpc-v2.md
RFC002 needs some additional text as well:
>### Abstract
>
> todo
> V1 RFCs are no longer a draft

- rfc/rfc011-verifiable-credential.md
- rfc/rfc014-authorization-credential.md
removed reference to v2 context.
Backport to V1 branch
> RFC011: refer to Nuts v1 JSON-LD context

- SUMMARY.md
- rfc/rfc001-nuts-start-architecture.md
- rfc/rfc002-authentication-token.md
- rfc/rfc003-oauth2-authorization.md
- rfc/rfc004-verifiable-transactional-graph.md
- rfc/rfc005-distributed-network-using-grpc.md
- rfc/rfc006-distributed-registry.md
- rfc/rfc008-certificate-structure.md
- rfc/rfc011-verifiable-credential.md
- rfc/rfc012-nuts-organization-credential.md
- rfc/rfc013-vc-irma-proof.md
- rfc/rfc014-authorization-credential.md
- rfc/rfc015-node-identity.md
- rfc/rfc017-distributed-network-grpc-v2.md
> v1 changes

- rfc/rfc002-authentication-token.md
> fix correct IRMA attrs for contract signing

- rfc/rfc011-verifiable-credential.md
fixes #221 
Will add issue to nuts-node after merge for migrating custom VC validation to something configurable/runtime.
> add validation requirements to RFC011

- rfc/rfc017-distributed-network-grpc-v2.md
> Clarify private tx payload inclusion in TransactionList

- rfc/rfc017-distributed-network-grpc-v2.md
> update rfc017 with security considerations from rfc005

- rfc/rfc001-nuts-start-architecture.md
> legal feedback

- rfc/rfc017-distributed-network-grpc-v2.md
copied and adapted from RFC005 §6
closes #252
closes #254
> RFC017: Add connections section

- rfc/rfc014-authorization-credential.md
> RFC014: Remove legalBase

- rfc/rfc020-authorization-credential-extension.md
Assurencelevel -> Assurancelevel
> Fix typo in rfc020

- rfc/rfc021-vp_token-grant-type.md
> change audience in rfc021

- rfc/rfc012-nuts-organization-credential.md
73 is not a valid number of minutes ;p
> Use a valid timestamp in the Organization Credential example
