- rfc/rfc003-oauth2-authorization.md
Closes #20 
create 2 issues after merge:
- set correct `aud` in bearer token nuts-foundation/nuts-node#83
- do correct contract validation with NutsOrganizationCredential
> rfc003 changes due to rfc011/rfc012

- rfc/rfc004-verifiable-transactional-graph.md
Closes #30
The choice for parallel updates is determined by information of the transaction compared to application data and previous transactions.
The proposed changes should be checked with application logic currently in the master branch of the node.
> replace timeline concept with generic updates&ordering

- rfc/rfc005-distributed-network-using-grpc.md
The order or operation does not matter when XOR-ing because all orders yield the same result.
> RFC005: Remove ordering when XOR-ing

- rfc/rfc006-distributed-registry.md
To be able to create DIDs without storing a private key.
When stolen, a private key could branch from a historic transaction and always change the DID Document.
> RFC006: change requirements for keys when creating DID Document

- rfc/rfc006-distributed-registry.md
This makes it way easier to compare keys with DIDs.
Also RFC7638 is easier to understand when using different keys.
> changed to DID generation

- rfc/rfc002-authentication-token.md
* Use the non-gendered pronoun `their` instead of `its` to reference a person. I don't know if Nuts has a style guide for text, but it may make sense to exclusively use its for lifeless objects (eg. a JWT).
* Fixes a few typos: clearity, exaple, etc.
* Change list items to all end with a period or make none end with a period.
Most of the changes are in the UZI section because that's what I was reading. I don't mind make a full pass of the document if you want.
> Minor edit for pronouns, typos, and consistent lists

- rfc/rfc005-distributed-network-using-grpc.md
Because out-of-order makes it very hard to process on the receiver's end.
> RFC005: Assert that all previous transactions are present before adding them to the DAG

- rfc/rfc005-distributed-network-using-grpc.md
Currently we've specified that duplicate connections must be avoided, but we haven't spec'd how. This lead to a bug in the Nuts Node.
This change specifies what to do when a second (duplicate) connection occurs.
> RFC005: Specified duplicate connection handling

- rfc/rfc006-distributed-registry.md
Closes #78 
URIs that start with `did` are references.
The limitation of a compound service that needs to reference absolute endpoints has been removed.
> RFC006: Expand service references

- rfc/rfc003-oauth2-authorization.md
As the JWT is being used as an authorization grant the term "JWT Grant" is probably more suitable (instead of JWT Bearer Token).
> Rename JWT Bearer Token -> JWT Grant in Oauth2 spec

- rfc/rfc003-oauth2-authorization.md
- rfc/rfc014-authorization-credential.md
closes #55 
closes #101 
`purposeOfUse` is the new service/policy/bolt term for an access policy.
It can be found in the oauth flow and in authorization credentials.
RFC003 now also adds a requirement for a Bolt: describe the desired user context per accessible resource.
A resource may be only accessible with a authorization credential but that doesn't mean it requires a logged in user. `userContext` is used to distinguish between the 2.
> consequences of 'public' policy only requests

- rfc/rfc014-authorization-credential.md
Closes #111 
changes `restrictions` in the authorization credential to 'resources'. Adding resources is a better fit than restricting.
added `localParameters` which can be of use to the issuer/custodian.
> Iss111 rfc014 additions

- rfc/rfc006-distributed-registry.md
Fixed earlier in Nuts Node but appearantely we forgot to fix it in the specs.
> RFC006: Fix incorrect DID Document transaction payload type

- rfc/rfc014-authorization-credential.md
Should be `path` instead of `resource`
> Fix key name for path in resources of a NutsAuthorizationCredential

- rfc/rfc006-distributed-registry.md
Decision made by https://github.com/nuts-foundation/nuts-node/issues/340
> RFC006: service references must use /serviceEndpoint as path

- rfc/rfc005-distributed-network-using-grpc.md
Closes #140 
nodes that only speak the v1 protocol should ignore transaction content when the transaction has the `to` header. This indicates that it's a private VC
> add limitation to V1 protocol for to header

- rfc/rfc004-verifiable-transactional-graph.md
- rfc/rfc016-lamport-clock.md
required for #126
This PR adds a new transaction version and changes to processing behaviour.
Introduction to the new TX version will have to be 2 fold:
- enable processing of new TXs and apply virtual lamport clocks
- enable creation of new TXs
> added rfc016: lamport clocks

- rfc/rfc015-node-identity.md
part of #137.
I'm not sure where to describe the encrypted `to` header for private DAG payloads. This might be part of the V2 protocol? Or does it need it's own RFC?
> added rfc for node identity

- rfc/rfc004-verifiable-transactional-graph.md
Specifies how private transactions are encoded.
TODO:
Fixes https://github.com/nuts-foundation/nuts-specification/issues/155
> RFC004: Private transactions

- rfc/rfc014-authorization-credential.md
closes #143 
`credentialSubject.evidence` is no longer mandatory.
After merge:
> made evidence field optional

- rfc/rfc003-oauth2-authorization.md
It'll now be a VerifiablePresentation in JSON format.
> remove base64 encoding from login contract presentation in token request

- rfc/rfc013-vc-irma-proof.md
~While working on the POC it felt like `NutsIrmaCredentialProof` wasn't the best name because `Nuts` is implied and `CredentialProof` is a little bit to generic. I'd like to rename it to `IRMASignatureProof` as that's what it is. It's a proof for IRMA credentials based on the IRMA signature.~
Edit: updated to `NutsIRMASignatureProof2022`
> Rename IRMA proof type name

- rfc/rfc005-distributed-network-using-grpc.md
Currently implemented as minversion = 1.3
> RFC005: Change TLS 1.2 requirement to 1.3

- rfc/rfc004-verifiable-transactional-graph.md
The `prevs` header is complicated enough for its own chapter. 😏 Some definitions are a bit more formal (and hopefully correct) now.
> RFC004 clarify prevs with dedicaded chapter

- rfc/rfc006-distributed-registry.md
Update examples to match section 4.2
> A reference MUST use the `type` query parameter to specify the type of the referenced service. The URI path MUST be set to `/serviceEndpoint` indicating it refers the `serviceEndpoint` field of the service.
> RFC006: fix paths for service references

- rfc/rfc008-certificate-structure.md
The Registration Authorities to be supported are KPN, QuoVadis and UZI.
The others (not to be supported) are Digidentity B.V. (meant for accountancy firms communicating with the tax office) and ZOVAR (zorgkantoren communicating with health insurers).
> RFC008: Explicitly specify which RAs are to be supported

- rfc/rfc004-verifiable-transactional-graph.md
Mention that the `lc` property stand for Lamport's Clock.
Clarify what "only use one" means and implies.
> RFC004 clarify lc + lc drops

- rfc/rfc008-certificate-structure.md
apparently there were already some changes on v1, but not on the main branch. Including the actual list of certificates can be used as confirmation by implementers, so I think the change still has value.
back port of #272
> RFC008: backport trust chain updates to v1

- rfc/rfc022-discovery-service.md
Was there a reason behind this claim? Perhaps a remnant from when retractions didn't have their own VP type?
If the requirement stays it should be implemented
> RFC022: Remove expiration time requirement on retractions

- rfc/rfc023-x509credential.md
It's not specified by did:x509, and we don't need it for validation. Just take the first certificate from x5c, as specified by RFC 7515.
> RFC023: Remove usage of x5t#S256
